"use client";

/* eslint-disable @typescript-eslint/no-unused-expressions -- compact immutable Set toggles */

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";

type Supplier = { id: string; name: string; status: string; contract_count: number; document_count: number };
type Contract = { id: string; title: string; status: string; current_version: number; origin: string; expiration_date?: string; supplier_name?: string; pending_proposals: number };
type Document = { id: string; title: string; category: string; visibility: string; status: string; expiration_date?: string; extraction_status: string; supplier_organization_id?: string; supplier_name?: string; filename: string; content_type: string; byte_size: number };
type Template = { id: string; name: string; contract_type: string; filename: string; fields: string | Array<{ key: string; label: string; required: boolean }> };
type ClauseModule = { id: string; name: string; heading: string; body: string };
type Alert = { id: string; kind: string; severity: string; title: string; message: string; due_at?: string; status: string };
type Workspace = { organization: { id: string; name: string }; suppliers: Supplier[]; contracts: Contract[]; documents: Document[]; templates: Template[]; clauseModules: ClauseModule[]; alerts: Alert[] };
type Extraction = { run: { id: string; status: string; model?: string } | null; fields: Array<{ id: string; field_key: string; value: string; confidence: number; source_reference?: string; corrected_value?: string }>; clauses: Array<{ id: string; clause_type: string; heading: string; clause_text: string; confidence: number; source_reference?: string }> };

const tabs = ["overview", "customers", "documents", "templates", "search", "alerts"] as const;
type Tab = typeof tabs[number];
const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const templateFields = (template?: Template) => { if (!template) return []; if (Array.isArray(template.fields)) return template.fields; try { return JSON.parse(template.fields) as Array<{ key: string; label: string; required: boolean }>; } catch { return []; } };

export default function ManagePage() {
  const router = useRouter();
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [tab, setTab] = useState<Tab>("overview"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [docForm, setDocForm] = useState({ title: "", category: "insurance_certificate", visibility: "shared", supplierOrganizationId: "", effectiveDate: "", expirationDate: "" }); const [docFile, setDocFile] = useState<File | null>(null);
  const [templateForm, setTemplateForm] = useState({ name: "", contractType: "msa" }); const [templateFile, setTemplateFile] = useState<File | null>(null);
  const [selectedTemplateId, setSelectedTemplateId] = useState(""); const [contractTitle, setContractTitle] = useState(""); const [templateValues, setTemplateValues] = useState<Record<string, string>>({});
  const [selectedClauseIds, setSelectedClauseIds] = useState<string[]>([]);
  const [query, setQuery] = useState(""); const [search, setSearch] = useState<{ mode?: string; results: Array<Record<string, unknown>> }>({ results: [] }); const [reindexing, setReindexing] = useState(false);
  const [reviewDocument, setReviewDocument] = useState<Document | null>(null); const [extraction, setExtraction] = useState<Extraction | null>(null); const [fieldCorrections, setFieldCorrections] = useState<Record<string, string>>({}); const [rejected, setRejected] = useState<Set<string>>(new Set());

  const load = useCallback(async () => { const response = await fetch("/api/v2/workspace", { cache: "no-store" }); if (response.status === 401) { router.push("/owner/login?return_to=/manage"); return; } const result = await response.json() as Workspace & { error?: string }; if (!response.ok) { setMessage(result.error ?? "Unable to load workspace"); return; } setWorkspace(result); setSelectedTemplateId((current) => current || result.templates[0]?.id || ""); }, [router]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const selectedTemplate = workspace?.templates.find((item) => item.id === selectedTemplateId); const selectedFields = useMemo(() => templateFields(selectedTemplate), [selectedTemplate]);

  async function uploadDocument(event: React.FormEvent) { event.preventDefault(); if (!docFile) return; setBusy(true); setMessage(""); const form = new FormData(); Object.entries(docForm).forEach(([key, value]) => value && form.set(key, value)); form.set("document", docFile); const response = await fetch("/api/v2/documents", { method: "POST", body: form }); const result = await response.json() as { error?: string }; setBusy(false); setMessage(response.ok ? "Document added to the vault." : result.error ?? "Upload failed"); if (response.ok) { setDocFile(null); setDocForm((value) => ({ ...value, title: "", effectiveDate: "", expirationDate: "" })); await load(); } }
  async function uploadTemplate(event: React.FormEvent) { event.preventDefault(); if (!templateFile) return; setBusy(true); const form = new FormData(); form.set("name", templateForm.name); form.set("contractType", templateForm.contractType); form.set("document", templateFile); const response = await fetch("/api/v2/templates", { method: "POST", body: form }); const result = await response.json() as { error?: string }; setBusy(false); setMessage(response.ok ? "Template uploaded and placeholders detected." : result.error ?? "Template upload failed"); if (response.ok) { setTemplateFile(null); await load(); } }
  async function generateContract(event: React.FormEvent) { event.preventDefault(); if (!selectedTemplate || !workspace?.suppliers[0]) return; setBusy(true); const response = await fetch("/api/v2/contracts/from-template", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ templateId: selectedTemplate.id, title: contractTitle, supplierOrganizationId: workspace.suppliers[0].id, values: templateValues, clauseModuleIds: selectedClauseIds }) }); const result = await response.json() as { error?: string }; setBusy(false); setMessage(response.ok ? "Contract generated and added to the negotiation workspace." : result.error ?? "Generation failed"); if (response.ok) { setContractTitle(""); setTemplateValues({}); setSelectedClauseIds([]); await load(); } }
  async function openExtraction(document: Document, run = false) { setBusy(true); if (run) { const response = await fetch(`/api/v2/documents/${document.id}/extraction`, { method: "POST" }); if (!response.ok) { const result = await response.json() as { error?: string }; setMessage(result.error ?? "Extraction failed"); setBusy(false); return; } } const response = await fetch(`/api/v2/documents/${document.id}/extraction`, { cache: "no-store" }); setExtraction(await response.json() as Extraction); setReviewDocument(document); setBusy(false); }
  async function confirmExtraction() { if (!reviewDocument || !extraction) return; setBusy(true); const response = await fetch(`/api/v2/documents/${reviewDocument.id}/extraction/confirm`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ fields: extraction.fields.map((field) => ({ id: field.id, status: rejected.has(field.id) ? "rejected" : "confirmed", correctedValue: fieldCorrections[field.id] ?? field.value })), clauses: extraction.clauses.map((clause) => ({ id: clause.id, status: rejected.has(clause.id) ? "rejected" : "confirmed" })) }) }); const result = await response.json() as { error?: string }; setBusy(false); setMessage(response.ok ? "Extraction confirmed and added to the knowledge base." : result.error ?? "Confirmation failed"); if (response.ok) { setReviewDocument(null); setExtraction(null); setRejected(new Set()); await load(); } }
  async function runSearch(event: React.FormEvent) { event.preventDefault(); const response = await fetch(`/api/v2/search?q=${encodeURIComponent(query)}`, { cache: "no-store" }); const result = await response.json() as typeof search & { error?: string }; if (response.ok) setSearch(result); else setMessage(result.error ?? "Search failed"); }
  async function rebuildSearchIndex() { setReindexing(true); setMessage(""); const response = await fetch("/api/v2/search/reindex", { method: "POST" }); const result = await response.json() as { available?: boolean; indexed?: number; pending?: number; error?: string }; setReindexing(false); if (!response.ok) { setMessage(result.error ?? "Semantic indexing failed"); return; } setMessage(result.available ? `${result.indexed ?? 0} search ${result.indexed === 1 ? "entry" : "entries"} indexed${result.pending ? `; ${result.pending} still pending` : ""}.` : "Semantic indexing is unavailable; keyword search remains active."); if (query.trim().length >= 2) { const refresh = await fetch(`/api/v2/search?q=${encodeURIComponent(query)}`, { cache: "no-store" }); if (refresh.ok) setSearch(await refresh.json() as typeof search); } }
  async function updateAlert(id: string, action: string) { await fetch(`/api/v2/alerts/${id}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action }) }); await load(); }

  if (!workspace) return <main className="v2-loading"><span className="portal-spinner"/><p>Preparing your vendor workspace…</p></main>;
  const expiring = workspace.alerts.filter((item) => item.kind === "expiration_due" || item.kind === "expired" || item.kind === "renewal_due").length;
  return <main className="v2-shell">
    <aside className="v2-sidebar"><Link className="v2-brand" href="/"><span className="brand-mark">P</span><strong>Pactline</strong></Link><div className="v2-org"><small>Vendor workspace</small><b>{workspace.organization.name}</b></div><nav>{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}><span>{({ overview: "⌂", customers: "◇", documents: "▤", templates: "□", search: "⌕", alerts: "!" } as Record<Tab, string>)[item]}</span>{titleCase(item)}{item === "alerts" && workspace.alerts.length > 0 && <em>{workspace.alerts.length}</em>}</button>)}</nav><div className="v2-side-bottom"><Link href="/">← Contract workspace</Link><Link href="/portal" target="_blank">Open customer portal ↗</Link></div></aside>
    <section className="v2-main"><header className="v2-header"><div><small>Vendor workspace</small><h1>{titleCase(tab)}</h1></div><div className="v2-header-actions"><span>Customer demo access is available in the Customer Portal.</span><Link href="/">Open negotiation</Link></div></header>{message && <div className="v2-message" role="status"><span>{message}</span><button onClick={() => setMessage("")}>×</button></div>}
      {tab === "overview" && <div className="v2-content"><section className="v2-metrics"><article><small>Customer relationships</small><strong>{workspace.suppliers.length}</strong><span>Connected companies</span></article><article><small>Contracts</small><strong>{workspace.contracts.length}</strong><span>{workspace.contracts.filter((item) => item.status !== "locked").length} active workflows</span></article><article><small>Vault documents</small><strong>{workspace.documents.length}</strong><span>{expiring} expiring soon</span></article><article className={workspace.alerts.length ? "attention" : ""}><small>Open alerts</small><strong>{workspace.alerts.length}</strong><span>Renewal and compliance</span></article></section><section className="v2-panel"><div className="v2-panel-head"><div><small>Portfolio</small><h2>Contract lifecycle</h2></div><button onClick={() => setTab("documents")}>Add document</button></div><div className="v2-contract-list">{workspace.contracts.map((contract) => <article key={contract.id}><span className="word-icon">W</span><div><strong>{contract.title}</strong><small>{contract.supplier_name ?? "Customer"} · {titleCase(contract.origin)} · Version {contract.current_version}</small></div><span className={`v2-status ${contract.status}`}>{contract.status}</span><b>{contract.pending_proposals ? `${contract.pending_proposals} edits` : "Up to date"}</b></article>)}</div></section></div>}
      {tab === "customers" && <div className="v2-content"><section className="v2-panel"><div className="v2-panel-head"><div><small>External companies</small><h2>Customer directory</h2></div></div><div className="v2-supplier-grid">{workspace.suppliers.map((supplier) => <article key={supplier.id}><span>{supplier.name.split(" ").map((word) => word[0]).join("").slice(0, 2)}</span><div><h3>{supplier.name}</h3><p>{supplier.contract_count} contracts · {supplier.document_count} documents</p></div><em>{supplier.status}</em></article>)}</div></section></div>}
      {tab === "documents" && <div className="v2-content v2-two-column"><section className="v2-panel"><div className="v2-panel-head"><div><small>Authoritative files</small><h2>Document vault</h2></div></div><div className="v2-doc-list">{workspace.documents.map((document) => <article key={document.id}><span className={document.content_type === "application/pdf" ? "pdf-icon" : "word-icon"}>{document.content_type === "application/pdf" ? "PDF" : "W"}</span><div><strong>{document.title}</strong><small>{titleCase(document.category)} · {document.supplier_name ?? "Vendor only"}{document.expiration_date ? ` · Expires ${document.expiration_date}` : ""}</small></div><span className={`v2-extraction ${document.extraction_status}`}>{titleCase(document.extraction_status)}</span><div className="v2-row-actions"><a href={`/api/v2/documents/${document.id}/download`}>Download</a><button disabled={busy} onClick={() => void openExtraction(document, document.extraction_status === "not_started" || document.extraction_status === "failed")}>{document.extraction_status === "not_started" ? "Extract" : "Review"}</button></div></article>)}</div></section><form className="v2-panel v2-form" onSubmit={uploadDocument}><small>Add to vault</small><h2>Upload document</h2><label>Title<input value={docForm.title} onChange={(event) => setDocForm({ ...docForm, title: event.target.value })} required /></label><label>Customer<select value={docForm.supplierOrganizationId} onChange={(event) => setDocForm({ ...docForm, supplierOrganizationId: event.target.value })}><option value="">Vendor only</option>{workspace.suppliers.map((supplier) => <option value={supplier.id} key={supplier.id}>{supplier.name}</option>)}</select></label><label>Category<select value={docForm.category} onChange={(event) => setDocForm({ ...docForm, category: event.target.value })}>{["msa","nda","sow","cloud_agreement","po","invoice","insurance_certificate","minority_business_certificate","other"].map((item) => <option key={item} value={item}>{titleCase(item)}</option>)}</select></label><div className="v2-form-row"><label>Effective date<input type="date" value={docForm.effectiveDate} onChange={(event) => setDocForm({ ...docForm, effectiveDate: event.target.value })}/></label><label>Expiration date<input type="date" value={docForm.expirationDate} onChange={(event) => setDocForm({ ...docForm, expirationDate: event.target.value })}/></label></div><label className="v2-drop">DOCX or PDF<input type="file" accept=".docx,.pdf,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event) => { const file = event.target.files?.[0] ?? null; setDocFile(file); if (file && !docForm.title) setDocForm({ ...docForm, title: file.name.replace(/\.[^.]+$/, "") }); }}/><span>{docFile?.name ?? "Choose a document"}</span></label><button className="v2-primary" disabled={busy || !docFile}>{busy ? "Uploading…" : "Add to vault"}</button></form></div>}
      {tab === "templates" && <div className="v2-content v2-two-column"><form className="v2-panel v2-form" onSubmit={uploadTemplate}><small>Reusable source</small><h2>Upload Word template</h2><p>Use placeholders such as <code>{"{{customer_name}}"}</code> and <code>{"{{effective_date}}"}</code>.</p><label>Template name<input value={templateForm.name} onChange={(event) => setTemplateForm({ ...templateForm, name: event.target.value })} required /></label><label>Contract type<input value={templateForm.contractType} onChange={(event) => setTemplateForm({ ...templateForm, contractType: event.target.value })} required /></label><label className="v2-drop">DOCX template<input type="file" accept=".docx" onChange={(event) => setTemplateFile(event.target.files?.[0] ?? null)}/><span>{templateFile?.name ?? "Choose template"}</span></label><button className="v2-primary" disabled={busy || !templateFile}>Upload template</button><div className="v2-template-list">{workspace.templates.map((template) => <button type="button" key={template.id} className={selectedTemplateId === template.id ? "active" : ""} onClick={() => setSelectedTemplateId(template.id)}><strong>{template.name}</strong><small>{template.filename} · {templateFields(template).length} fields</small></button>)}</div></form><form className="v2-panel v2-form" onSubmit={generateContract}><small>Vendor initiated</small><h2>Generate contract</h2>{selectedTemplate ? <><label>Template<select value={selectedTemplateId} onChange={(event) => setSelectedTemplateId(event.target.value)}>{workspace.templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label><label>Contract title<input value={contractTitle} onChange={(event) => setContractTitle(event.target.value)} required /></label>{selectedFields.map((field) => <label key={field.key}>{field.label}<input value={templateValues[field.key] ?? ""} onChange={(event) => setTemplateValues({ ...templateValues, [field.key]: event.target.value })} required={field.required}/></label>)}<button className="v2-primary" disabled={busy || !contractTitle}>Generate version one</button></> : <div className="v2-empty">Upload a template to begin.</div>}</form></div>}
      {tab === "search" && <div className="v2-content"><section className="v2-search-hero"><small>Contract knowledge base</small><h2>Search across confirmed clauses and metadata</h2><form onSubmit={runSearch}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Which agreements require $2 million in insurance?"/><button disabled={query.trim().length < 2}>Search</button></form><div className="v2-search-meta"><p>Results are limited to authoritative content in this customer workspace.</p><button type="button" disabled={reindexing} onClick={() => void rebuildSearchIndex()}>{reindexing ? "Rebuilding…" : "Rebuild semantic index"}</button></div></section><section className="v2-search-results">{search.mode && <small>{titleCase(search.mode)} results</small>}{search.results.map((result) => <article key={String(result.id)}><div><span>{titleCase(String(result.category ?? "document"))}</span><h3>{String(result.title)}</h3></div><p>{String(result.content)}</p><a href={`/api/v2/documents/${String(result.document_id)}/download`}>Open source document</a></article>)}{search.mode && search.results.length === 0 && <div className="v2-empty search-empty"><strong>No confirmed matches</strong><p>{search.mode === "keyword" ? "No indexed semantic matches were available, and the keyword fallback did not find this wording." : "The semantic index did not find a matching confirmed clause or field."}</p><small>Confirm a document extraction, rebuild the semantic index, or try a broader phrase.</small></div>}</section></div>}
      {tab === "alerts" && <div className="v2-content"><section className="v2-panel"><div className="v2-panel-head"><div><small>Deterministic monitoring</small><h2>Renewal and compliance alerts</h2></div><button onClick={() => void fetch("/api/v2/alerts/refresh", { method: "POST" }).then(load)}>Refresh checks</button></div><div className="v2-alert-list">{workspace.alerts.length ? workspace.alerts.map((alert) => <article key={alert.id} className={alert.severity}><span>!</span><div><small>{titleCase(alert.kind)}{alert.due_at ? ` · ${alert.due_at}` : ""}</small><h3>{alert.title}</h3><p>{alert.message}</p></div><div><button onClick={() => void updateAlert(alert.id, "acknowledge")}>Acknowledge</button><button onClick={() => void updateAlert(alert.id, "resolve")}>Resolve</button></div></article>) : <div className="v2-empty">No active renewal or compliance alerts.</div>}</div></section></div>}
    </section>
    {reviewDocument && extraction && <div className="v2-modal-backdrop"><section className="v2-modal" role="dialog" aria-modal="true" aria-labelledby="extraction-title"><header><div><small>Human confirmation required</small><h2 id="extraction-title">Review {reviewDocument.title}</h2><p>{extraction.run?.model ?? "Extraction"} · AI output cannot affect alerts until confirmed.</p></div><button onClick={() => setReviewDocument(null)}>×</button></header><div className="v2-review-scroll"><h3>Extracted fields</h3>{extraction.fields.map((field) => <article key={field.id} className={rejected.has(field.id) ? "rejected" : ""}><div><strong>{titleCase(field.field_key)}</strong><small>{field.confidence}% confidence · {field.source_reference ?? "Source unavailable"}</small></div><input value={fieldCorrections[field.id] ?? field.value} onChange={(event) => setFieldCorrections({ ...fieldCorrections, [field.id]: event.target.value })}/><button onClick={() => setRejected((current) => { const next = new Set(current); next.has(field.id) ? next.delete(field.id) : next.add(field.id); return next; })}>{rejected.has(field.id) ? "Restore" : "Reject"}</button></article>)}<h3>Extracted clauses</h3>{extraction.clauses.map((clause) => <article key={clause.id} className={`v2-clause-review ${rejected.has(clause.id) ? "rejected" : ""}`}><div><strong>{clause.heading}</strong><small>{titleCase(clause.clause_type)} · {clause.confidence}% confidence · {clause.source_reference ?? "Source unavailable"}</small><p>{clause.clause_text}</p></div><button onClick={() => setRejected((current) => { const next = new Set(current); next.has(clause.id) ? next.delete(clause.id) : next.add(clause.id); return next; })}>{rejected.has(clause.id) ? "Restore" : "Reject"}</button></article>)}</div><footer><button onClick={() => setReviewDocument(null)}>Review later</button><button className="v2-primary" disabled={busy || !extraction.run} onClick={() => void confirmExtraction()}>Confirm approved information</button></footer></section></div>}
    {tab === "templates" && workspace.clauseModules.length > 0 && <aside className="v2-clause-picker"><small>Optional clause library</small><h3>Add to generated agreement</h3>{workspace.clauseModules.map((clause) => <label key={clause.id}><input type="checkbox" checked={selectedClauseIds.includes(clause.id)} onChange={() => setSelectedClauseIds((current) => current.includes(clause.id) ? current.filter((id) => id !== clause.id) : [...current, clause.id])}/><span><b>{clause.heading}</b><em>{clause.body}</em></span></label>)}</aside>}
  </main>;
}
