"use client";

/* eslint-disable @next/next/no-html-link-for-pages -- brand links deliberately perform a clean portal exit */

import { useCallback, useEffect, useState } from "react";

type PortalContract = { id: string; title: string; status: string; current_version: number; origin: string; expiration_date?: string; permission: string; pending_proposals: number };
type PortalDocument = { id: string; title: string; category: string; status: string; expiration_date?: string; extraction_status: string; filename: string; content_type: string };
type PortalWorkspace = { account: { displayName: string; organizationName: string; username: string }; contracts: PortalContract[]; documents: PortalDocument[]; alerts: Array<{ id: string; severity: string; title: string; message: string; due_at?: string }> };
type Review = { contract: PortalContract; blocks: Array<{ id: string; kind: string; current_text: string }>; proposals: Array<{ id: string; block_id: string; proposed_text: string; counter_text?: string; status: string }>; agreements: Array<{ party_id: string; version_number: number }>; reviewer: { partyId: string; permission: string } };
const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function SupplierPortalPage() {
  const [workspace, setWorkspace] = useState<PortalWorkspace | null>(null); const [credentials, setCredentials] = useState({ username: "supplier.reviewer", password: "" }); const [busy, setBusy] = useState(true); const [message, setMessage] = useState(""); const [tab, setTab] = useState<"contracts" | "documents" | "alerts">("contracts");
  const [review, setReview] = useState<Review | null>(null); const [drafts, setDrafts] = useState<Record<string, string>>({}); const [editing, setEditing] = useState<string | null>(null); const [submission, setSubmission] = useState({ title: "", file: null as File | null }); const [submissionOpen, setSubmissionOpen] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/portal/workspace", { cache: "no-store" }); if (response.ok) setWorkspace(await response.json() as PortalWorkspace); setBusy(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function login(event: React.FormEvent) { event.preventDefault(); setBusy(true); const response = await fetch("/api/portal/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(credentials) }); const result = await response.json() as { error?: string }; if (!response.ok) { setMessage(result.error ?? "Sign-in failed"); setBusy(false); return; } setMessage(""); await load(); }
  async function logout() { await fetch("/api/portal/logout", { method: "POST" }); setWorkspace(null); setReview(null); }
  async function openContract(id: string) { setBusy(true); const response = await fetch(`/api/portal/contracts/${id}`, { cache: "no-store" }); const result = await response.json() as Review & { error?: string }; setBusy(false); if (!response.ok) { setMessage(result.error ?? "Unable to open contract"); return; } setReview(result); setDrafts({}); setEditing(null); }
  async function submitProposals() { if (!review) return; const edits = Object.entries(drafts).map(([blockId, proposedText]) => ({ blockId, originalText: review.blocks.find((block) => block.id === blockId)?.current_text, proposedText })); if (!edits.length) return; setBusy(true); const response = await fetch(`/api/portal/contracts/${review.contract.id}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ baseVersion: review.contract.current_version, edits }) }); const result = await response.json() as { error?: string }; setBusy(false); setMessage(response.ok ? `${edits.length} proposed change${edits.length === 1 ? "" : "s"} sent to the contract owner.` : result.error ?? "Unable to submit changes"); if (response.ok) await openContract(review.contract.id); }
  async function agree() { if (!review) return; setBusy(true); const response = await fetch(`/api/portal/contracts/${review.contract.id}/agree`, { method: "POST" }); const result = await response.json() as { error?: string; locked?: boolean }; setBusy(false); setMessage(response.ok ? result.locked ? "Both parties agreed. The final document is locked." : "Your approval is recorded for this version." : result.error ?? "Unable to agree"); if (response.ok) await openContract(review.contract.id); }
  async function submitAgreement(event: React.FormEvent) { event.preventDefault(); if (!submission.file) return; setBusy(true); const form = new FormData(); form.set("title", submission.title); form.set("document", submission.file); const response = await fetch("/api/portal/submissions", { method: "POST", body: form }); const result = await response.json() as { error?: string }; setBusy(false); setMessage(response.ok ? "Agreement submitted to the customer workspace." : result.error ?? "Submission failed"); if (response.ok) { setSubmissionOpen(false); setSubmission({ title: "", file: null }); await load(); } }
  if (busy && !workspace) return <main className="supplier-loading"><span className="portal-spinner"/><p>Opening supplier portal…</p></main>;
  if (!workspace) return <main className="supplier-login"><form onSubmit={login}><a href="/" className="v2-brand"><span className="brand-mark">P</span><strong>Pactline</strong></a><span className="supplier-lock">◇</span><h1>Supplier portal</h1><p>Access every agreement and shared document assigned to your company.</p><label>Username<input value={credentials.username} onChange={(event) => setCredentials({ ...credentials, username: event.target.value })} autoComplete="username"/></label><label>Password<input type="password" value={credentials.password} onChange={(event) => setCredentials({ ...credentials, password: event.target.value })} autoComplete="current-password" placeholder="SupplierDemo!2026"/></label>{message && <div className="portal-message error">{message}</div>}<button disabled={busy}>{busy ? "Signing in…" : "Sign in securely"}</button><small>Demo credentials: supplier.reviewer / SupplierDemo!2026</small></form></main>;
  if (review) {
    const locked = review.contract.status === "locked"; const agreed = review.agreements.some((item) => item.party_id === review.reviewer.partyId && item.version_number === review.contract.current_version);
    return <main className="supplier-review"><header><button onClick={() => setReview(null)}>← All contracts</button><div><small>{workspace.account.organizationName}</small><h1>{review.contract.title}</h1><p>Version {review.contract.current_version} · {titleCase(review.contract.status)}</p></div><button onClick={logout}>Sign out</button></header>{message && <div className="supplier-notice">{message}</div>}<section className="supplier-review-layout"><div className="supplier-document"><div className="supplier-doc-head"><span className="word-icon">W</span><div><strong>Collaborative Word document</strong><small>Your edits are proposals and cannot overwrite the owner’s version.</small></div>{locked && <a href={`/api/portal/contracts/${review.contract.id}/download`}>Download final</a>}</div><div className="supplier-paper">{review.blocks.map((block, index) => <article key={block.id} className={`supplier-block ${block.kind} ${editing === block.id ? "editing" : ""}`}><small>{String(index + 1).padStart(2, "0")}</small><div>{editing === block.id ? <textarea value={drafts[block.id] ?? block.current_text} onChange={(event) => setDrafts({ ...drafts, [block.id]: event.target.value })}/> : block.kind === "title" ? <h2>{block.current_text}</h2> : block.kind === "heading" ? <h3>{block.current_text}</h3> : <p>{block.current_text}</p>}</div>{!locked && review.reviewer.permission === "propose_changes" && block.kind !== "title" && <button onClick={() => { if (editing === block.id) setEditing(null); else { setEditing(block.id); setDrafts({ ...drafts, [block.id]: drafts[block.id] ?? block.current_text }); } }}>{editing === block.id ? "Done" : "Edit"}</button>}</article>)}</div></div><aside className="supplier-review-rail"><small>Review round</small><h2>Your proposals</h2>{review.proposals.length ? review.proposals.map((proposal) => <article key={proposal.id}><span>{titleCase(proposal.status)}</span><p>{proposal.proposed_text}</p>{proposal.counter_text && <div><b>Owner counter</b>{proposal.counter_text}</div>}</article>) : <div className="v2-empty">No proposals submitted yet.</div>}<div className="supplier-review-actions"><button className="v2-primary" disabled={busy || locked || !Object.keys(drafts).length} onClick={() => void submitProposals()}>Submit proposed changes</button><button disabled={busy || locked || agreed || review.proposals.some((item) => item.status === "pending")} onClick={() => void agree()}>{agreed ? "Approval recorded" : "Approve this version"}</button></div></aside></section></main>;
  }
  return <main className="supplier-shell"><header><a href="/" className="v2-brand"><span className="brand-mark">P</span><strong>Pactline supplier portal</strong></a><div><span>{workspace.account.displayName}</span><small>{workspace.account.organizationName}</small></div><button onClick={logout}>Sign out</button></header><nav>{(["contracts","documents","alerts"] as const).map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{titleCase(item)}{item === "alerts" && workspace.alerts.length > 0 && <em>{workspace.alerts.length}</em>}</button>)}</nav>{message && <div className="supplier-notice">{message}</div>}<section className="supplier-content">
    {tab === "contracts" && <><div className="supplier-heading"><div><small>Company agreements</small><h1>Contracts</h1><p>Current and expired agreements in one secure workspace.</p></div><button onClick={() => setSubmissionOpen((value) => !value)}>+ Submit supplier agreement</button></div>{submissionOpen && <form className="supplier-submission" onSubmit={submitAgreement}><label>Agreement title<input value={submission.title} onChange={(event) => setSubmission({ ...submission, title: event.target.value })} required/></label><label>DOCX document<input type="file" accept=".docx" onChange={(event) => setSubmission({ ...submission, file: event.target.files?.[0] ?? null })}/><span>{submission.file?.name ?? "Choose a Word agreement"}</span></label><button className="v2-primary" disabled={busy || !submission.file}>Submit to customer</button></form>}<div className="supplier-contract-grid">{workspace.contracts.map((contract) => <article key={contract.id}><div><span className="word-icon">W</span><em className={`v2-status ${contract.status}`}>{contract.status}</em></div><h2>{contract.title}</h2><p>Version {contract.current_version} · {titleCase(contract.origin)}</p><small>{contract.expiration_date ? `End date ${contract.expiration_date}` : "No end date recorded"}</small><button onClick={() => void openContract(contract.id)}>{contract.permission === "view" ? "View agreement" : "Open review"}</button></article>)}</div></>}
    {tab === "documents" && <><div className="supplier-heading"><div><small>Shared records</small><h1>Document vault</h1><p>Contracts, transactional records, and compliance certificates.</p></div></div><div className="supplier-document-list">{workspace.documents.map((document) => <article key={document.id}><span className={document.content_type === "application/pdf" ? "pdf-icon" : "word-icon"}>{document.content_type === "application/pdf" ? "PDF" : "W"}</span><div><h3>{document.title}</h3><p>{titleCase(document.category)} · {document.filename}</p></div><em className={`v2-status ${document.status}`}>{document.status}</em><small>{document.expiration_date ? `Expires ${document.expiration_date}` : "No expiration"}</small><a href={`/api/portal/documents/${document.id}/download`}>Download</a></article>)}</div></>}
    {tab === "alerts" && <><div className="supplier-heading"><div><small>Action center</small><h1>Renewal and compliance</h1><p>Prompts are calculated from confirmed document dates and requirements.</p></div></div><div className="supplier-alerts">{workspace.alerts.length ? workspace.alerts.map((alert) => <article key={alert.id} className={alert.severity}><span>!</span><div><h3>{alert.title}</h3><p>{alert.message}</p>{alert.due_at && <small>Due {alert.due_at}</small>}</div></article>) : <div className="v2-empty">No active alerts for your company.</div>}</div></>}
  </section></main>;
}
